### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by savchenko** [randombits-dev/fontable#28]
https://cdn.jsdelivr.net/npm/fontable@latest/dist/auto.js returns the following:

```js
import { initFontPicker as i } from "./index.js";
i();
```

Obviously, from client's perspective `index.js` is nil.

**Comment by nienow** [comment]
Thanks for reporting this. If you import it as a module, it should work:
```
<script type="module" src="https://cdn.jsdelivr.net/npm/fontable@latest/dist/auto.js"></script>
```

I need to at least change the documentation, but it would be better if it didn't require modules in the first place.

**Comment by nienow** [comment]
It turned out to be easy to change it to not require a module, so the original url should now work (when jsdelivr refreshes its cache)
